services:
  - type: web
    name: rpg-vault
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rpg-vault-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /

databases:
  - name: rpg-vault-db
    databaseName: rpg_vault
    user: rpg_vault_user